# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .  # Use the current directory for Dockerfile and code
      dockerfile: Dockerfile  # Specify the Dockerfile with multi-stage build
    ports:
      - "5000:5000"  # Expose the app on port 5000
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
